// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY5XFm1Eoi7qIg_zx7HReWQwzkVTz0rN8',
    appId: '1:738054677288:web:8ef26709faed1be197a61d',
    messagingSenderId: '738054677288',
    projectId: 'vesatogo-app-608bd',
    authDomain: 'vesatogo-app-608bd.firebaseapp.com',
    storageBucket: 'vesatogo-app-608bd.appspot.com',
    measurementId: 'G-FV0H6160JD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJIbnsh8SDvdelKizjuhNtrJ45dqmR7pw',
    appId: '1:738054677288:android:2581beca58f68eb297a61d',
    messagingSenderId: '738054677288',
    projectId: 'vesatogo-app-608bd',
    storageBucket: 'vesatogo-app-608bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7NkutVBYYj4oSERuwsIkul9hhSNv-8W0',
    appId: '1:738054677288:ios:7bc51d3f686c3eb397a61d',
    messagingSenderId: '738054677288',
    projectId: 'vesatogo-app-608bd',
    storageBucket: 'vesatogo-app-608bd.appspot.com',
    iosBundleId: 'com.example.vesatogoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7NkutVBYYj4oSERuwsIkul9hhSNv-8W0',
    appId: '1:738054677288:ios:7bc51d3f686c3eb397a61d',
    messagingSenderId: '738054677288',
    projectId: 'vesatogo-app-608bd',
    storageBucket: 'vesatogo-app-608bd.appspot.com',
    iosBundleId: 'com.example.vesatogoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY5XFm1Eoi7qIg_zx7HReWQwzkVTz0rN8',
    appId: '1:738054677288:web:b3ec7f3c1c11c1b497a61d',
    messagingSenderId: '738054677288',
    projectId: 'vesatogo-app-608bd',
    authDomain: 'vesatogo-app-608bd.firebaseapp.com',
    storageBucket: 'vesatogo-app-608bd.appspot.com',
    measurementId: 'G-BP263JYEQX',
  );
}
