// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCStRCdmj4eN-Dhu8Jvd5S1jto7pmyZp7k',
    appId: '1:280299586424:web:cbd7ecec2232adfa05be8d',
    messagingSenderId: '280299586424',
    projectId: 'vesatogoapp-c33dc',
    authDomain: 'vesatogoapp-c33dc.firebaseapp.com',
    storageBucket: 'vesatogoapp-c33dc.appspot.com',
    measurementId: 'G-V2ZDYK35SH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNbw4_IfIlTfm7oE6_1b4ktvHq4RLvqAA',
    appId: '1:280299586424:android:4ea1ec397d1ec30605be8d',
    messagingSenderId: '280299586424',
    projectId: 'vesatogoapp-c33dc',
    storageBucket: 'vesatogoapp-c33dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDABeCrR1cu6jSmaIpZFoRVbC_2d1SYaM',
    appId: '1:280299586424:ios:0e758ed313936da305be8d',
    messagingSenderId: '280299586424',
    projectId: 'vesatogoapp-c33dc',
    storageBucket: 'vesatogoapp-c33dc.appspot.com',
    iosBundleId: 'com.example.vesatogoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDABeCrR1cu6jSmaIpZFoRVbC_2d1SYaM',
    appId: '1:280299586424:ios:0e758ed313936da305be8d',
    messagingSenderId: '280299586424',
    projectId: 'vesatogoapp-c33dc',
    storageBucket: 'vesatogoapp-c33dc.appspot.com',
    iosBundleId: 'com.example.vesatogoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCStRCdmj4eN-Dhu8Jvd5S1jto7pmyZp7k',
    appId: '1:280299586424:web:31fc4d4dc88160bd05be8d',
    messagingSenderId: '280299586424',
    projectId: 'vesatogoapp-c33dc',
    authDomain: 'vesatogoapp-c33dc.firebaseapp.com',
    storageBucket: 'vesatogoapp-c33dc.appspot.com',
    measurementId: 'G-67RH31RE81',
  );
}
